# This file is used to configure your service on Render

services:
  - type: web
    name: askfinance-backend
    root: server
    build:
      # Command to install dependencies
      command: |
        pip install -r requirements.txt
    start: uvicorn server.main:app --host 0.0.0.0 --port 8000
    env: python
    plan: free
