services:
  - type: web
    name: askfinance-backend
    root: server          # Point to the root folder of your backend (server)
    build:
      # Command to install dependencies
      command: |
        pip install -r requirements.txt
    start: uvicorn app.main:app --host 0.0.0.0 --port 8000  # Point to app.main for FastAPI
    env: python
    plan: free
